# Generated by Django 4.2.10 on 2024-02-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
